# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Note: these secrets are invalid because the website is no longer hosted.
development:
  secret_key_base: 67296ff905cf2dd49ca5df2dda56363f99cda15aaee71266586394a8c63da2c096c63af925aaf84d13844f8d995c34a87f383e3967ad69841dbe154f23e25193
test:
  secret_key_base: eba2b32f0396b490d309022bb73517dafba77782da0ee15d4104d35fed5dd382ba98646c4ea993a52343635403defcab66036b3859b277ac2de90b1a32695f00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
